commands:
  # Time
  - command:
    input: What time is it?
    entity: time
    action: getTime
  - command:
    input: Tell me the time
    entity: time
    action: getTime
  # Date
  - command:
    input: What is today's date?
    entity: time
    action: getDate
  - command:
    input: Tell me the date.
    entity: time
    action: getDate
  # Year
  - command:
    input: Tell me what year it is
    entity: time
    action: getYears
  - command:
    input: Which year is it?
    entity: time
    action: getYear
  # Weather
  - command:
    input: What's the weather?
    entity: time
    action: getWeather
  - command:
    input: What's the weather like?
    entity: time
    action: getWeather
  - command:
    input: How hot is it?
    entity: time
    action: getWeather
  - command:
    input: How cold is it?
    entity: time
    action: getWeather    
  
  # Open
  - command:
    input: Open Google
    entity: open
    action: google












  
